### ISSUE TITLE
7.) Fix Fee Structure

### ISSUE THREAD

**Issue by 4x13** [Veil-Project/veil#109]
Fix fee structure (fee’s are supposed to be variable based on the tx size correct?) same for the zerocoin fee??

**Comment by 4x13** [comment]
![fee-issue](https://user-images.githubusercontent.com/39984029/50555003-497d4280-0c7a-11e9-93c1-de99334d2aa0.png)

**Comment by 4x13** [comment]
I sent 10 veil to myself and the fee is .67 veil.

**Comment by 4x13** [comment]
![fee-issue-2](https://user-images.githubusercontent.com/39984029/50555009-76315a00-0c7a-11e9-9536-b50a85e9cc28.png)

**Comment by 4x13** [comment]
![fee-issue-3](https://user-images.githubusercontent.com/39984029/50555013-93662880-0c7a-11e9-832b-258e6d97e978.png)

**Comment by presstab** [comment]
Can you see what the fee is displayed as using `gettransaction` rpc. As I mentioned above, the GUI seems to be off by two decimals.

**Comment by 4x13** [comment]
![fee-issue-4](https://user-images.githubusercontent.com/39984029/50555543-e80da180-0c82-11e9-859d-09d6a67a46c0.png)

ok, I see what you mean, it is off by 4 decimal places..

**Comment by 4x13** [comment]
ok, I see what you mean, it is off by 4 decimal places..

**Comment by ianGre** [comment]
A couple more screen shots in a slightly different scenario. I hesitate to put this in a separate issue, because I think this is related. When sending a variety of transaction sizes, aside from the fees all being off by some decimal places, one of the spends for 0.09 showed and calculated as 0.9, and only showed as the 0.09 when viewed in the block explorer https://testnet.veil-project.com/address/mvU5sCU9SwycQwXeHaC9Ci4W8KpCKkmYuL 

Notice in the spend screen **behind** the pop-up window, it shows 0.09. When clicking transaction detail it **still** shows 0.9004480, this time adding the proper fee amount (except for where the fee is displaye separately).
![screen shot 2019-01-02 at 3 57 36 pm](https://user-images.githubusercontent.com/36124423/50580958-110f7b80-0ea9-11e9-8a4f-db572b4ebc05.png)
![screen shot 2019-01-02 at 3 58 15 pm](https://user-images.githubusercontent.com/36124423/50580995-68155080-0ea9-11e9-9217-ef615ee3e2c7.png)

**Comment by ianGre** [comment]
This gives you a view of all the transactions I sent, in PDF in case the Testnet Block Explorer is not available later.

[Veil Testnet Explorer- wallet transactions (more confs).pdf](https://github.com/Veil-Project/veil/files/2719956/Veil.Testnet.Explorer-.wallet.transactions.more.confs.pdf)

**Comment by presstab** [comment]
93430bd5b6fb5ce5d26bf70d5d91ca116783ee23
