### ISSUE TITLE
Wallet allows manual minting of less than 10 Veil or non-multiple of 10 (like 11)

### ISSUE THREAD

**Issue by MisterKangaroo** [Veil-Project/veil#162]
see description.
Wallet should tell the user that the minimal minting-able amount is 10.

**Comment by StrontiumZ38** [comment]
Did you replicate this? Looks like tab's already on it anyway.

**Comment by MisterKangaroo** [comment]
Can't replicate since i have no mainnet coins...
but it appeared several times in chat and PT seems to know and working on it

**Comment by ianGre** [comment]
I have just seen this FIX in v1.0.0.3 committed a few minutes ago!

**Comment by ianGre** [comment]
Before this issue gets closed, the wallet update tonight that prevents minting less than 10, ... someone in the chat minted 11! And it cost him an extra 1 Veil in fee. That is, 1.1 instead of 0.1. Um, need to ensure an amount that can be made up entirely in the denom choices, or will they get the change back in RingCT?

**Comment by StrontiumZ38** [comment]
This can be closed now @4x13

**Comment by MisterKangaroo** [comment]
are you sure @StrontiumZ38? Read that a user minted 12 Veil some minutes ago...
cant test it myself without funds in the wallet...

**Comment by presstab** [comment]
4aeee3fda4fe1b4bf04bd6fc3f03bb25464fe43d
a9d8c1e1e263678db34a0d47a6f8b20f0f9451a5
