### ISSUE TITLE
 CreateNewBlock: invalid block created. Stake is not zerocoinspend

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#193]
Haven't got much info on this but several users seem to feel staking isn't active despite being 'active'. This is from one such user.
2019-01-03T07:45:30Z ERROR: CreateNewBlock: invalid block created. Stake is not zerocoinspend! 
2019-01-03T07:45:30Z CreateNewBlock(): block weight: 6244 txs: 5 fees: 4176520 sigops 407 Proof-Of-Stake:0 
and this one i also see often: "SelectStakeCoins: FOUND 2 STAKABLE ZEROCOINS",

[debug_part_1.txt](https://github.com/Veil-Project/veil/files/2729311/debug_part_1.txt)

Others with substantial amount of veil are not getting rewards where others with far less are frequently. This could just be bad luck and unrelated, but better you guys are aware of this.

**Comment by StrontiumZ38** [comment]
![image](https://user-images.githubusercontent.com/38264865/50722137-a90d9f00-110d-11e9-8ef2-29fa640f1387.png)

**Comment by 4x13** [comment]
what exactly do you see as an issue in that image?

**Comment by StrontiumZ38** [comment]
I'm not sure. I've no idea what's to be expected as normal in this case. 
![image](https://user-images.githubusercontent.com/38264865/50723236-378a1c80-111e-11e9-96b9-941163788538.png)
I just know people with a lot of veil are getting no stakes while others with far fewer are killing it.

**Comment by veilgets** [comment]
many people are also getting this error:  "ERROR: AcceptToMemoryPoolWithTime: failed to accept tx to mempool: coinstake" what does that mean? is that normal?

**Comment by JoenPool** [comment]
because many people are busy with my questions here maybe some more/important information. The .txt file in the openingspost is a part of my Desktop debug.
On the desktop i received (mining and staking since the first second) 2x basecoin transaction and 2x zerocoin mint. I was wondering if staking was working correct because nothing happens.
I decided to get an fresh laptop and installed the latest Veil release fresh.
Now this is the result on the laptop:
![veil 660](https://user-images.githubusercontent.com/46398822/50724656-91c0b880-10f1-11e9-8bac-8c95cd2285c8.jpg)
[debug around stake time[663].txt](https://github.com/Veil-Project/veil/files/2729507/debug.around.stake.time.663.txt)

Also the balance what is showed on the laptop is now 8 higher then on the desktop (i just received an new transaction, u cant see on the picture).
Next: i receive different basecoin transactions what are 100% not my, but 2 of them get confirmed and showed in my balance.

Ps. the 2nd message from Strontium, that picture made with an patato, is not my system (is from another member i guess).

I hope this information can helps u further because if u only replace the new release (2 folders are inside that zip) the update wont work proparly. I guess the fresh laptop of my proofs that.

**Comment by JoenPool** [comment]
> 
> 
> because many people are busy with my questions here maybe some more/important information. The .txt file in the openingspost is a part of my Desktop debug.
> On the desktop i received (mining and staking since the first second) 2x basecoin transaction and 2x zerocoin mint. I was wondering if staking was working correct because nothing happens.
> I decided to get an fresh laptop and installed the latest Veil release fresh.
> Now this is the result on the laptop:
> ![veil 660](https://user-images.githubusercontent.com/46398822/50724656-91c0b880-10f1-11e9-8bac-8c95cd2285c8.jpg)
> [debug around stake time[663].txt](https://github.com/Veil-Project/veil/files/2729507/debug.around.stake.time.663.txt)
> 
> Also the balance what is showed on the laptop is now 8 higher then on the desktop (i just received an new transaction, u cant see on the picture). Also during syncing on the laptop i saw my confirmed balance around the 400-500 then back to 140 etc etc.
> Next: i receive different basecoin transactions what are 100% not my, but 2 of them get confirmed and showed in my balance.
> 
> Ps. the 2nd message from Strontium, that picture made with an patato, is not my system (is from another member i guess).
> 
> I hope this information can helps u further because if u only replace the new release (2 folders are inside that zip) the update wont work proparly. I guess the fresh laptop of my proofs that.

EDIT!!:
i can keep repeating this and getting different transactions on the wallet.
What i did: i clean installed Veil on my laptop as i told. First time starting i select: IMPORT WALLET
i choose the wallet.dat on my USB drive and everytime i do this i get totally different transactions and a other receiving SV adress.

**Comment by ianGre** [comment]
Looking at the second debug.log screenshot, it seems to have a completely different problem, or a problem where the first one didn't. What is "stake is not zerocoin spend!"?

Also, please check Joen's latest edit just above this one. Thanks Joen, for the testing!

I've been testing staking and mining on testnet, but clearly the dynamics and competition cannot be compared. We had not problem doing either, testnet. Maybe the algorithm regarding stake denominations needs to be revisited, with a careful consideration of our _real world_ results??

**Comment by StrontiumZ38** [comment]
I believe this is resolved. Closing
