### ISSUE TITLE
Synchronization screen on Mac OS X is green

### ISSUE THREAD

**Issue by gabrielnergaard** [Veil-Project/veil#220]
Running 1.0.0.6 on MacOS X 10.14.2, the synchronization screen is showing up as green:

![](https://clipz.in/6pmn7.png)

**Comment by ianGre** [comment]
Who else had this issue? Just wondering. I've never seen it on my Mac Pro with MacOS 10.13.

**Comment by seanPhill** [comment]
We've established that, of staff, only Gabe and Alex have seen this. Meanwhile #241 duplicates this?

**Comment by seanPhill** [comment]
This had NEVER happened to me (on High Sierra), but after the latest Mac "security" update 2019-001 (not to Mojave) this now affects my iMac! My Mac Pro is still good, as I have not installed that update yet!!

**Comment by seanPhill** [comment]
On further consideration, I'm not sure whether this update actually did that to the iMac. I didn't have the iMac in this country when the issue was looked at earlier. It arrived fairly recently.
The difference might only be that the iMac is a Mac with an (inbuilt) Apple monitor!
The Mac Pro doesn't have an Apple monitor, it just has a HDMI and DVI video outputs. Both send output to a generic monitor (with lower resolution than an Apple monitor), that does not have the graphic problem with the synchronisation screen.
