### ISSUE TITLE
Base coin address not restored when restoring seed phrase

### ISSUE THREAD

**Issue by pcartwright81** [Veil-Project/veil#261]
After clearing data folder and restoring with seed phrase the base coin address is not restored. Windows X64 Version  1.0.6.  When adding TX address the funds are not available, however the transactions show.

**Comment by seanPhill** [comment]
I have been informed that the wallet will still detect the incoming funds, even if the particular addresses have not been (re)generated after restoring the wallet from seed.

The correct procedure is to (re)create each address in the exact same order that they were created in the first place. 

It is a good idea to keep a record of which type of address is created and in which order, because if the third address created, for example, is a stealth address, when the third address on the original wallet was a basecoin address, then it will appear differently.

**Comment by furszy** [comment]
That is not the "correct procedure". It's a bug. A priority one.

The correct procedure is generate different accounts for the each address type on the derivation path and/or improve the restoration discovery process.

**Comment by seanPhill** [comment]
Maybe I should have said a "known workaround".

**Comment by pcartwright81** [comment]
I used importaddress "address".   Found in the console

**Comment by presstab** [comment]
Importaddress only sets it as a watch only address. You should try generating a lot of basecoin addresses so that it will recalculate your previous address (use console command `getnewbasecoinaddress`). Then use `rescanblockchain`.

**Comment by presstab** [comment]
Have not been able to reproduce.

**Comment by pcartwright81** [comment]
I again reproduced this by renaming my data folder to data.old.  Then I restore with the seed phrase.  I can never get the same basecoin address back.  This is by using getnewbasecoinaddress multiple times.

**Comment by pcartwright81** [comment]
After the third time of doing the restore from passphrase I can see the funds, but the address is not there.  Last time it stayed at 0 balance for 3 days
