### ISSUE TITLE
Long sync times

### ISSUE THREAD

**Issue by veilgets** [Veil-Project/veil#292]
users are reporting sync times of many hours. is this expected/can it be improved

**Comment by Strunczez** [comment]
Not syncing at all in my case. Ports forwarded.

**Comment by seanPhill** [comment]
(Advice for Strunczez) When I synced on the second run of the 1.0.0.10 wallet, I tried it with " -reindex-chainstate", because on the first run it detected a corrupted database, and automatically offered a rescan, which was not sufficient to sync properly.

During the some hours of syncing, (I had only previously had half of the chain downloaded), I had to occasionally try ```getbestblockhash``` and ```reconsiderblock <thebestblockhash>. The final time I had to invalidateblock for a block not found on the explorer (within one block of the explorer's top at the time.) 

Regarding the peer connections, many people had been peer banned and some people reported getting connections only after changing their IP address, presumably through a VPN. People were advised to ```clearbanned``` to help the situation.

**Comment by presstab** [comment]
Since there were so many people resyncing at the same time with `v1.0.0.10` it caused a slow down on the networking side of things. That being said, still have some work to do concerning syncing times.
