### ISSUE TITLE
Cannot Spend More than 10 Zerocoin to Basecoin

### ISSUE THREAD

**Issue by CryptoSifu** [Veil-Project/veil#346]
Trying to spend zerocoin (denominations of 10) to basecoin to remint into higher denoms

I expected it to send

If I try to spend more than 10 at a time, the error tells me "Try to spend with a higher security level to include more coins". error (code -4). Security Level is set at 100.
Command used is: spendzerocoin (amount) false true 100 (bv address) 10

Everytime

v1.0.1.4 from veil github

Win OS x64

2019-01-29T21:24:22Z ERROR: GenerateAccumulatorWitness failed to find mint 4e9964267d6a8e3d40939636471219dc2d933d0697b5bcaa9d1b001ce9a14b00 in blockchain db
2019-01-29T21:24:22Z ERROR: MintToTxIn : Try to spend with a higher security level to include more coins
2019-01-29T21:29:52Z ERROR: GenerateAccumulatorWitness failed to find mint 4e9964267d6a8e3d40939636471219dc2d933d0697b5bcaa9d1b001ce9a14b00 in blockchain db
2019-01-29T21:29:52Z ERROR: MintToTxIn : Try to spend with a higher security level to include more coins

**Comment by seanPhill** [comment]
help spendzerocoin

spendzerocoin amount mintchange minimizechange securitylevel d( "address" denomination)

(Admittedly, there is an issue reported where a security level above 100 has been accepted.)

I'm testing this now (to a testnet stealth address). It looked like I should do this: 

```spendzerocoin 820 false true 100 d( "tps1qqpqflrprregnh2hetfxlvhefe6vzygxk5axpyyjnfc7rrqu38fhlmspq2hvahmlve3pdc7xaqgwtxsfsdz5mn6huz4uwu356d2tw3x2f3c72qqq300k6l" 10)``` but that only got an error "Method not found (code -32601)"

```spendzerocoin 820 false true 100 ( "tps1qqpqflrprregnh2hetfxlvhefe6vzygxk5axpyyjnfc7rrqu38fhlmspq2hvahmlve3pdc7xaqgwtxsfsdz5mn6huz4uwu356d2tw3x2f3c72qqq300k6l" 10)``` seems to be working.

(At least there was no error, and the wallet has not given a result yet.

**Comment by seanPhill** [comment]
It's been working a lot, doing things like this 
```
2019-01-31T01:01:24Z GenerateAccumulatorWitness : 18150 mints added to witness
2019-01-31T01:01:30Z GenerateAccumulatorWitness: generating
``` , but it might not complete, as I've just lost all but one peer connection (and I just noticed a 21 second time discrepancy.

**Comment by seanPhill** [comment]
Okay it finally completed, and I don't think the fact that I did this test spend to a stealth address would make any difference to the result, as the format of you command is not what was successful here (as shown in my earlier response). The output of the command shows you that this is possible to a stealth address too, as you should try using stealth (standard Veil) addresses rather than basecoin. (If you can't mint your amount all at once with your CT and RingCT balance, then you can always (for now) send it to basecoin (500 at a time) to do the mint .
[tmp-zc-sv-tx.txt](https://github.com/Veil-Project/veil/files/2815339/tmp-zc-sv-tx.txt)

**Comment by 4x13** [comment]
I have noticed that when this issue occurs, using just resetmintedzerocojns and resetspentzerocoins should fix the issue consistently

**Comment by CryptoSifu** [comment]
Whenever I resetmintedzerocoins and resetspentzerocoins in previous wallet builds my balances disappeared in GUI. Has this issue been resolved. It’s a hassle to always be restoring from seed and waiting hours for searchdeterministic to complete.

**Comment by seanPhill** [comment]
You should not need to be continually restoring from seed. You wallet should not be getting corrupted regularly. You can do a search without resetting your blockchain.

Also, I suspect that the format of the spendzerocoin command (as I have given it to you above) is different than it used to be, since the addition of denomination specification, which would explain the number of people who reported errors trying to spendzerocoin without the brackets or quotation marks.

**Comment by CryptoSifu** [comment]
Restored from seed using discord snapshot and recovery commands. 
Was able to send after that. 
Strange though as I had done these steps prior to writing up this issue with no change to result. 
Only difference this time was another user snapshot.
