### ISSUE TITLE
Unlock for staking only

### ISSUE THREAD

**Issue by 4x13** [Veil-Project/veil#467]
We need to implement the ' Unlock for Staking only ' option in the wallet. Seems this was an oversight on my part in the first release of the UX/UI

**Comment by presstab** [comment]
Not sure what you are talking about here.

![Screenshot from 2019-04-02 13-22-32](https://user-images.githubusercontent.com/6628210/55430240-cefae200-554a-11e9-8508-d13270fe09ed.png)
![Screenshot from 2019-04-02 13-21-09](https://user-images.githubusercontent.com/6628210/55430245-d15d3c00-554a-11e9-9f26-739338aa39b1.png)

There is #315 open for some issues with it though. You need to be more specific on what this issue is supposed to address.
