### ISSUE TITLE
RingCt to Zerocoin Mint Bug: "AddAnonInputs_Inner: Insufficient funds."

### ISSUE THREAD

**Issue by Rock-N-Troll** [Veil-Project/veil#471]
When minting from **ringCT** to **Zerocoin Mint**, sometimes when trying to create a zerocoin mint(s) immediately after the **11** confirmations necessary for it to show up in the zerocoin mint GUI, it will fail with the following error:

`2019-xx-xxTxx:xx:xxZ ERROR: AddAnonInputs_Inner: Insufficient funds.`
`2019-xx-xxTxx:xx:xxZ ERROR: AddAnonInputs_Inner: Insufficient funds.`

I have tested with many different balances and it seems to happen all the time. At first, I thought changing the value was what was fixing it but it might actually have just been waiting for 1 extra confirmation.

**UPDATE**: 
It appears to be an off by 1 error as per my testing results.

to reproduce: wait until exactly **11** confirmations after a **ringCT** to **Zerocoin Mint** where the change is returned to the wallet balance. At exactly **11** confirmations, it will show up in the minting GUI pop-up.

If you click mint when there are **11** confirmations, you will get the following error: 

![image](https://user-images.githubusercontent.com/34344520/55448344-62f19b80-5595-11e9-9694-dc06ae98e06f.png)

However, if you keep clicking mint with the same mint value in the mint textbox, eventually the next block comes in and it succeeds (most likely because I suspect it now has **12** confirmations which is a check in the mint code but not in the GUI display code)

Also, on at least one occasion got a dummy transaction that displays as "**Converted RingCt to Basecoin**" which remains unconfirmed even now:

`2019-xx-xxTxx:xx:xxZ ERROR: CheckZerocoinMint() : PubCoin does not validate`
`2019-xx-xxTxx:xx:xxZ ERROR: CheckStandardOutput: zerocoin mint check failed`
`2019-xx-xxTxx:xx:xxZ ERROR: CommitTransaction(): Transaction cannot be broadcast immediately,  (code 0)`

**Comment by seanPhill** [comment]
I would agree with this. I don't know exactly about the eleven, but when I get this error I just wait two minutes and try again.

**Comment by CryptoSifu** [comment]
I also have this issue. 
In addition, now I cannot mint or spend any of the ringct or ct coins. 

I topped up my ringct balance to over 10 in an attempt to mint the balance instead of send it.
Now that my balance is over 10 ringct I cannot mint from ringct or ct balances.

It appears to try spending/minting from the ringct balance first.
Since that fails and the balance never reduces, it doesn't look to minting from the available ct balance.
So I have to send from ct back to basecoin then mint and deal with the accumulation of more unspendable ct and ringct.

I will probabaly just load a new wallet and send everything I can over until there is a fix that frees up the unspendable ringct coins.

Send me a message if you need any technical details.
