### ISSUE TITLE
Standardize sending coins from Debug Console

### ISSUE THREAD

**Issue by HORT-VEIL** [Veil-Project/veil#514]
All the sending coin commands from the debug console should be in the same format if possible.

Can zerocoin spends be put in this format:
 
sendzerocoin address amount
 
and have 'false true 100' set as default without having to enter them in command?

So:
sendzerocoin amount address
sendstealthtobasecoin amount address
sendringcttobasecoin  amount address
sendbasecointoaddress amount address
sendbasecointostealth amount address
sendringcttostealth amount address

**Comment by seanPhill** [comment]
You want to take the "p" out of the spendzerocoin command? I found it very convenient for the autocomplete that when I am spending zerocoins I would not have to worry about five other forms of moving Veil around, trying to get in my autocomplete.

Also, zerocoin is the standard SPEND command, so it starts with spend, whereas the others are usually used for SENDing Veil from one bucket to another, or from your exchange account to your self, or vice-versa. So I would actually prefer the commands as they are. With the SPENDzerocoin command distinct and easily auto-completed.

That's just my personal preference.

Also, for easily using the command without specifying the boolean options, that's already what the GUI does. So you can always use the GUI spend page. Sorry to pop your bubble. ;)

Also, as real world usage increases (that is not only sending to exchanges and reminting), we are even going to have to add minor complexity to the spend page, to give people the choice of minting (or not minting) change to zerocoins. (That relates to another issue I saw.)

Lastly, in case anyone *accidentally* chose the wrong command, it provides a kind of fail-safe to have amount and address for _spending_ zerocoin and address and amount for _sending_ UTXOs. As you've already got them confused above. ;)

**Comment by Rock-N-Troll** [comment]
Only change I can suggest after further consideration is:

**spendzerocoin** amount address
sendstealthtobasecoin amount address
sendringcttobasecoin amount address
sendbasecointoaddress amount address
sendbasecointostealth amount address
sendringcttostealth amount address

The function names follow the same "X to Y" format which makes sense for "send".

Eventually spends to basecoin, spends to ringct, and spends to stealth will be phased out anyway. 
he flow will most likely only allow basecoin to be converted up into RingCT or CT, and CT to be converted up into RingCT. And finally, Zerocoin and RingCT will be the only 2 forms allowed (unless you still have basecoin/CT that hasn't been converted).

So eventually, these will be removed because the network will enforce not being able to convert into basecoin anymore.

sendstealthtobasecoin amount address **(REMOVED)**
sendringcttobasecoin amount address **(REMOVED)**

**Comment by veilgets** [comment]
Bounty: 125

**Comment by HORT-VEIL** [comment]
This is no longer necessary as Veil is moving away from Zerocoin.
