### ISSUE TITLE
When hovering over "Start Veil Core on system login", the pop-up tooltip is not fully visible.

### ISSUE THREAD

**Issue by VeilDango** [Veil-Project/veil#54]
https://i.imgur.com/puTLH0Y.png

30.5. When hovering over "Start Veil Core on system login", the pop-up tooltip is not fully visible. It is cut off vertically.

Reproducibility:

I can reliably reproduce the issue. Refer to screenshot.

Version used:

https://github.com/Veil-Project/veil/releases/download/testnet-1/veil-0.0.9-win64-setup-unsigned.exe

Hardware and OS:

6700k Intel CPU
Pro 970 SSD
32GB RAM
Windows 10 Pro

Debug.log:

https://cdn.discordapp.com/attachments/507024857847037962/527898028942688256/debug.log

**Comment by 4x13** [comment]
This does not happen under Linux 64, says Veil

**Comment by StrontiumZ38** [comment]
Verticality on these tips is no longer a problem on one-liners. There remains some inconsistency on both horizontal and vertical space though 
![image](https://user-images.githubusercontent.com/38264865/52183778-cdfd4b00-284e-11e9-9167-27367f11f1f3.png)

This is not limited to these options, but across tooltips in the wallet. Perhaps it would be better to simply have one issue addressing this universal problem, but I'll leave devs to determine that.

**Comment by StrontiumZ38** [comment]
@veildev I've looked into this and found it to be a common problem faced by Windows users with Qt. It seems the easiest workaround is to simply remove the font size from css customisation and use the default style font size. Currently you have the css specify a 13 font size on tooltip text. I imagine it wouldn't hurt much to use default size, but I'll leave that decision up to you rather than submit a pr in case you have other ideas.

**Comment by StrontiumZ38** [comment]
@veildev did you get a chance to look into this at all?

**Comment by presstab** [comment]
Bounty: 375

**Comment by veilgets** [comment]
developer: codeofalltrades
