### ISSUE TITLE
codablock Code Fix Suggestion: Add Additional Placeholder Entry To vtx For PoS (Currently Works For PoW)

### ISSUE THREAD

**Issue by Rock-N-Troll** [Veil-Project/veil#590]
[codablock](https://github.com/codablock) via Discord:

> going through a few changes/fixes I did when I tried out some staking a few months ago. One issue was that my staked blocks were rejected by my own node due to TX inputs missing. Looking at how you guys fixed in the mean time brings me to this: https://github.com/Veil-Project/veil/blame/master/src/miner.cpp#L311
> 
> The actual reason for the issue was a different thing however. When a PoS block is created (vs a PoW block), the transaction at index 1 is replaced with the coinstake TX: https://github.com/Veil-Project/veil/blame/master/src/miner.cpp#L393
> 
> But the original TX is actually a TX added by the block template code
> So if you replace it, TXs that depend on this one (spend an output from that one) and were also included in the same block would become invalid after the TX at index 1 is replaced
> Making the whole block invalid
> The correct fix would be to add an additional place holder entry to vtx, the same as done for PoW here: https://github.com/Veil-Project/veil/blame/master/src/miner.cpp#L144
> 
> So that you later replace the placeholder
> This should also allow you to revert the hotfix you did in line 311
> This should also fix the "issue" of the mempool not getting fully cleared when PoS blocks come in :wink:
> (btw, don't have time for a PR, so just writing this here so that someone can take it)

**Comment by veilgets** [comment]
Bounty: 854.17

**Comment by veilgets** [comment]
Developer: Codeofalltrades

**Comment by seanPhill** [comment]
This is a really old issue, but with the mentioned Hotfix still in place at line 311, I have **not seen** this problem in the years since this issue, despite having done countless amounts of staking on mainnet, testnet, and devnet. So, as this was presumably set aside as zerocoin-related when switching from zerocoin staking to ringct staking was made the priority, I think I will close this as was previously done, as this as it is does not appear to be responsible for any existing user difficulties. (Judging from the above, there was a PR #654 that was submitted, then Code Reviewed Complete, then back to Assigned Issues, then not tested because a new testnet was not ready at the time, and then abandoned (closed) due to "too many changes" (77 files changed!) on (compared to) the master branch, pending a new PR to be created, which does not appear to have been done.
