### ISSUE TITLE
Sending Zerocoin from sending tab calculates Fee unnecessary

### ISSUE THREAD

**Issue by Veil-Grumpy** [Veil-Project/veil#596]
Spending Zerocoin from sending tab calculate fee unnecessary since spending zerocoin doesn't cost any fee.

Check screenshot:
![calcfeelol](https://user-images.githubusercontent.com/46780798/57915192-8b58ff00-7890-11e9-87d7-f42d5fed5b5a.PNG)

Example:
Spending 50 zerocoin calculate a spending fee of 0.00000078 Veil

Sending works when you just enter the full amount ( 50 Veil ), so just a visual thing.

Windows 10

**Comment by seanPhill** [comment]
This function was here in case a fee would be put on spending zerocoins. One was proposed, splitting the minting fee, so that the 0.01 minting fee would be split into 0.005 for minting and 0.005 for spending, which would be used to incentivise the miners and stakers to include more zerocoin transactions in blocks.

**Comment by veilgets** [comment]
Bounty: 250

**Comment by veilgets** [comment]
Developer: codeofalltrades
