### ISSUE TITLE
Cut off tooltip

### ISSUE THREAD

**Issue by MisterKangaroo** [Veil-Project/veil#63]
Sometimes the tooltip cuts off and works again after another tooltip rendered fully.
Screenshot below:
![](https://cdn.discordapp.com/attachments/486350562011512834/528023449805783050/IMG_20181228_023609.jpg)

@veildev

**Comment by 4x13** [comment]
Which OS?? I do not have that on Linux 64

**Comment by MisterKangaroo** [comment]
its on win 10 x64

**Comment by MisterKangaroo** [comment]
1920x1080 px Resolution

**Comment by ianGre** [comment]
I noticed that too in Win 10 64-bit.

If you go from text label to text label tooltips are cut off at the top and the bottom. Keep changing what you are hovering over and eventually you get a full height tooltip and then the subsequent ones are okay.

**Comment by StrontiumZ38** [comment]
Can confirm same problem and 'remedy'.

**Comment by MisterKangaroo** [comment]
same problem still exists in the actual version testnet3
(win 10 x64, 1920x1080px res)


![](https://cdn.discordapp.com/attachments/523336739134242828/528424591949955081/IMG_20181229_050943.jpg)

**Comment by MisterKangaroo** [comment]
still actual in testnet9 (windows 10 x64)

**Comment by MisterKangaroo** [comment]
still actual in 1.0.0.4

**Comment by veildev** [comment]
check this when #196 is merged.

**Comment by StrontiumZ38** [comment]
@veildev since 1.0.0.6 this problem remains, but looks to have changed some in nature. I noticed in the commit that the space allowed was increased vertically, and this seems to be the case in practice. However some entries sometimes take two lines (inconsistent), and Settings reads currently as 'etting' (consistently), also sometimes parts of the word are cropped away (also inconsistent) like Send.
![image](https://user-images.githubusercontent.com/38264865/50733821-3c130b80-11d8-11e9-99e9-144e5b1bd3ff.png)
![image](https://user-images.githubusercontent.com/38264865/50733825-50570880-11d8-11e9-85a5-c0f8197f9306.png)
![image](https://user-images.githubusercontent.com/38264865/50733856-b479cc80-11d8-11e9-94d3-0682c7349207.png)
![image](https://user-images.githubusercontent.com/38264865/50733906-3f5ac700-11d9-11e9-91d3-42cf7af38ed1.png)
![image](https://user-images.githubusercontent.com/38264865/50733827-5d73f780-11d8-11e9-927b-f80279abca2a.png)
![image](https://user-images.githubusercontent.com/38264865/50733896-29e59d00-11d9-11e9-8f0e-1848e8e36550.png)
![image](https://user-images.githubusercontent.com/38264865/50733883-0ae70b00-11d9-11e9-9c92-709ca02aad07.png)

**Comment by seanPhill** [comment]
Are these messages displayed with pixels instead of text? There seems to be a lot of unselectable text in this wallet, and I wonder whether _this_ is due to the change from SVG to PNG a little while back??  OR, is it the graphics that are layering on top of the text? (with border thickness and the like)

**Comment by seanPhill** [comment]
More on the previous comment, I noticed in a Linux 32-bit VM that text, such as display of balance with more than 1 in thousands column was truncated at the left, that is that text is not scaled to fit containers regardless of the sizing. At least this was until I resized it as wide as i possibly could, and now I doubt its ability to show numbers in the tens of thousands. (I guess, wait for the SVG version to return, at least for scaling containers around whichever font size.)

**Comment by StrontiumZ38** [comment]
This is a universal problem on tooltip spacing/inconsistency thereof that has several issues dedicated to it. I'll let devs decide how to handle it, but it's probably best to condense to one issue to simplify things. @4x13 @veildev

**Comment by presstab** [comment]
Bounty: 666.67

**Comment by veilgets** [comment]
Developer: codeofalltrades
