### ISSUE TITLE
Coin control window crashes or misaligned in Mac.

### ISSUE THREAD

**Issue by ncrypter90** [Veil-Project/veil#642]
Alignment of coin control window does not pop up in full screen. If i restore down then it will lean to right where half of the window is invisible.

Works fine in Win 10 but failed in Mac.

Attached screen record videos from Mac (unzip attached file for videos).

[Archive.zip](https://github.com/Veil-Project/veil/files/3389672/Archive.zip)

**Comment by ncrypter90** [comment]
Test failed. issue still persists on main branch.
[31 Dec 2019 at 3:04:28 pm.mov.zip](https://github.com/Veil-Project/veil/files/4011905/31.Dec.2019.at.3.04.28.pm.mov.zip)

**Comment by seanPhill** [comment]
I've never noticed this failure of the Coin Control pop up (in macOS or elsewhere) before, because I have never ever thought of using the Qt wallet in **full screen**. 🤷 

Also, when trying to replicate this (on my 21" late-2013 iMac running macOS Catalina 10.15.7) I got a completely different pop-up problem than shown in the videos. Coin Control was not aligned over to the right, but only a tiny part of the vertical size of the Coin Control popup was visible.
However, ... I swung my mouse pointer up into the top left corner of the screen, which on my Mac activates MISSION CONTROL and then did the same thing again, deactivating Mission Control and the Coin Control was displayed perfectly!

I've never actually had anyone ask for help for this, and think that this issue or part of the original issue might never cause any real trouble. Maybe there has been a change in the Qt code since this (2019) issue, but what I found may be coincidental and unrelated to the original report?

Tested on Mac Pro (late-2013 running macOS Monterey 12.6.5) with a very ordinary 21" monitor at the monitor's default resolution (1600 x 900) and when opening Coin Control with the wallet in full screen no part of the Coin Control popup could be seen.

I did the same fix, of opening and closing Mission Control, and the Coin Control popup was then perfectly displayed in front of the wallet.

I tested this on an old (mid-2012, 13") MacBook Pro also running macOS Catalina, and got the exact same bug and easy fix as the iMac.

For **good measure** I tested this on another old 13" MacBook Pro running Ubuntu 22.04.2 LTS, because it is too old even for Catalina, and the bug does not exist on Ubuntu. (Actually on the Ubuntu MacBook I do run the Qt wallet in full screen mode, because the layout is not good in the existing space when in Windowed mode.

CLOSING this issue as too minor and unlikely to cause people inconvenience, that it won't be worth our time.
Anyone thinking of working on this will likely be much more motivated by more significant challenges.
