### ISSUE TITLE
Missing Veil coins 

### ISSUE THREAD

**Issue by mushak88** [Veil-Project/veil#793]
Hi guys , i have a problem with the veil wallet . I'ved deposited some veil for staking , but nothing happened for weeks  . So i'ved decided to witdraw my coins, the problem is the all my coins ( don't know how ) are not avaibile , but in the main page of the wallet  it says that a have total balance ... veil ( not market as unconfirmed or immature ) .  When i go to coin control on the send page , i can't see my coins . So gooing to zerocoin minting I can se my coins distributed in in zerocoin  (60%) and mintable ringCT (40%) . On the minting page i can't do nothing because i have no basecoin . What can i do to recover my veil coins (basecoins i think) and withdraw ?  .. I need to add that i have this transactions that i didn't make .. " zerocoin mint (n/a)  - 0.090000 veil  , zerocoin mint fron ringCT (n/a)  - 0.090000 veil ect. 

Pls someone help me , because i have a lot of coins stucked ok this wallet , that give me only problems .

**Comment by seanPhill** [comment]
This is normal wallet behaviour, because it is necessary for Veil to be converted to zerocoins for automatic staking. This process is automatic, by default. You can spend all of your coins from the Debug Console, available through Settings, Advanced Options, using commands that you can find either through the help in the Console or at this location: 
https://veil.freshdesk.com/support/solutions/articles/43000474291-different-methods-for-sending-coins-from-debug-console
For additional help or advice on sending your complete RingCT balance you can try:
`sendringcttobasecoin BVaddressOfExchange Amount "" "" TotalBalance`
If this fails, try spending about 1 Veil less (and don't include the parts of the command after Amount. Then wait for any  change to mature (become spendable) and try the longer form of the command, with the new total balance.

If you have any further questions please submit them at:
https://veil.freshdesk.com/support/home
after checking the guides that may be found there.

Also, please be aware that Veil has a significant update coming, where all Veil balances will be converted into a single stealth (RingCT) type, and will not have any other types that may confuse some people.

Zerocoin was originally chosen as the way to provide maximum privacy and for private staking.
RingCT will provide both functions in the future upgrade.

**Comment by mushak88** [comment]
Tks seanPhill , the link you seend was very useful and solved all my problems.
