### ISSUE TITLE
Taking forever to download

### ISSUE THREAD

**Issue by saahiluppal** [Veil-Project/veil#982]
Taking forever to download, on high speed internet.
almost 10 sec per block.

**Comment by seanPhill** [comment]
This is not actually a matter of the amount of data to download per block, but the amount of CPU power required to validate each block. This would have been considerably more difficult in the early 2019 blocks, before the zerocoins were lightened.
I agree, it would take a very very long time to load and validate each and every block since the genesis block, and it does make a big difference how much cpu power you have. People generally, probably almost without exception, download an official snapshot which you can find linked from the main website veil-project.com and from veil.tools.

**Comment by saahiluppal** [comment]
Alright, so there is a snapshot file available.
Thanks.
